### PR TITLE
Multi circuit view

### PR DESCRIPTION
**Pull request by DNA386**
- allow multiple circuits to be displayed side by side with correlated scrolling/zoom.

eg:
Screenshot 2024-08-19 at 17 18 22

### CODE REVIEW

**Review by CalMacCQ — COMMENTED** [review]
Noticed some inconsistencies in dark mode between the two circuits in the multi circuit view. I'm using Firefox.

Screenshot 2024-08-27 at 15 45 07

Also the burger menu looks to be a mixture of dark and light mode? Does this reproduce for you?


Screenshot 2024-08-27 at 16 12 58


Lastly....  is it possible to view any circuit side by side in the mutli circuit view? I can make a choice but then the UI doesn't change and just shows the "basic" circuit 

Screenshot 2024-08-27 at 16 14 49

**Comment by DNA386** [comment]
> Noticed some inconsistencies in dark mode between the two circuits in the multi circuit view. I'm using Firefox.

If you mean the background colour difference, that was intentional in order to help identify which circuit is which. Can be changed if that's confusing though!

> Also the burger menu looks to be a mixture of dark and light mode? Does this reproduce for you?

Do you mean the white icons? With the new theme, that is what the 'active' icons look like. Perhaps I can change the colour of the text to make it more obvious eg:
Screenshot 2024-08-27 at 16 28 40
Alternatively, I can add a check icon next to the menu item eg (but with a proper tick)
Screenshot 2024-08-27 at 16 34 46

> is it possible to view any circuit side by side in the mutli circuit view? I can make a choice but then the UI doesn't change and just shows the "basic" circuit

Yes, that's a bug - you can change the value from the storybook controls but both remain correlated - will add a fix

**Comment by CalMacCQ** [comment]
> If you mean the background colour difference, that was intentional in order to help identify which circuit is which. Can be changed if that's confusing though!

Ah okay. I guess it'll show up in `render_circuit_jupyter` version too then? I'm not sure what is best, just wanted to make sure it was intentional.

>  Do you mean the white icons? With the new theme, that is what the 'active' icons look like. Perhaps I can change the colour of the text to make it more obvious eg

Ah that makes sense! Maybe ticks would be better for this? I should've spotted that. I'm fine with either.

>  Yes, that's a bug - you can change the value from the storybook controls but both remain correlated - will add a fix 

Great :) thanks

**Comment by CalMacCQ** [comment]
Ticks look nice :) I prefer that to the black vs white entries in the burger menu.

> Yes, that's a bug - you can change the value from the storybook controls but both remain correlated - will add a fix

I'm not sure this fix is working for me yet. I can't seem to choose circuits in the multi circuit view

Screenshot 2024-08-27 at 18 24 23

**Comment by DNA386** [comment]
you should now be able to edit the 'circuit presets' entry in the `controls` section (unfortunately has to be typed manually since there's no built in type checking/selection for lists).

**Comment by CalMacCQ** [comment]
> you should now be able to edit the 'circuit presets' entry in the `controls` section (unfortunately has to be typed manually since there's no built in type checking/selection for lists).

Ah I see, I tried out a couple of examples typing in manually. Looks great :) 

Approved!

**Review by CalMacCQ — APPROVED** [review]

**Comment by CalMacCQ** [comment]
I see the concern with the wires. I'm fine with the original solution you proposed. If I think of anything better then I'll let you know :)

**Comment by DNA386** [comment]
or maybe can give full borders to alternate frames instead
Screenshot 2024-08-27 at 18 46 03

**Comment by DNA386** [comment]
(Ended up going with both border and colour change to make it look more intentional)

**Comment by CalMacCQ** [comment]
Thanks @DNA386 :) Looks good. 

Am I right in saying its possible to pass a list of circuits with len >2 to the circuit renderer and have the multi circuit view?

If I render more than two circuits side by side will colour change alternate?

**Comment by DNA386** [comment]
> Am I right in saying its possible to pass a list of circuits with len >2 to the circuit renderer and have the multi circuit view?
> 
> If I render more than two circuits side by side will colour change alternate?

yeah that's right.

**Review by CalMacCQ — APPROVED** [review]
Nice one! :)

**Pull request merged**
