### PR TITLE
Feature/navigator panel

### PR DESCRIPTION
**Pull request by DNA386**
Add in a navigator panel to the circuit renderer:
- Render options now collected under a menu
- Circuit navigation should work with keyboard, mouse scrolling and click interactions

Also:
- Fix gate name calculation to pick up custom circuit names when present.

Example:
Screenshot 2022-11-01 at 13 24 45

### CODE REVIEW

**Comment by aidanCQ** [comment]
Taking a look at this now 👍

**Comment by aidanCQ** [comment]
It may be worth adding the css property `select: none` to the slider to prevent ghost dragging.
https://user-images.githubusercontent.com/104831665/199250400-b58dbcdb-e926-408d-b50a-f21f3cbef5c8.mov

**Comment by aidanCQ** [comment]
When the slider is positioned at the start or end I couldn't immediately tell which region to click in order to move the slider. 
Screenshot 2022-11-01 at 14 07 04

Maybe the draggable section could be inset in the slider container?
Screenshot 2022-11-01 at 14 10 06

**Comment by aidanCQ** [comment]
I noticed that the sliders in `CircuitDisplayContainer/FromDOM` don't have a background gradient but the sliders in `Navigator/Circuit` do. Are these intended to be different?



Screenshot 2022-11-01 at 14 15 12
Screenshot 2022-11-01 at 14 07 04

**Comment by aidanCQ** [comment]
Liking the popover menu. 👍 

Screenshot 2022-11-01 at 14 17 17

**Comment by DNA386** [comment]
What browser are you using? The ghost dragging doesn't seem to happen when I try it (chrome/firefox/safari).

**Comment by DNA386** [comment]
the background was mostly there as an example that one can be supplied, but I thought it looked cleaner without one.

Ideally it would be nice to have a mini render of the actual circuit there but that would be a pretty large overhead for big circuits so I didn't add it in

**Comment by aidanCQ** [comment]
> What browser are you using? The ghost dragging doesn't seem to happen when I try it (chrome/firefox/safari).

I've tried reproducing (firefox) it but I can't do it consistently so it may not be that big of an issue.

**Comment by DNA386** [comment]
Ok.. When I try to do it it selects everything instead, so I'll at least remove that

**Comment by DNA386** [comment]
added rounded scrollbars to help decide which part is the scrollbar:
Screenshot 2022-11-01 at 16 23 42

Admittedly not super clear, but making it thinner makes it look uglier when it has no background so since thats how the circuits look I'd rather prioritise that

**Comment by DNA386** [comment]
Content of this PR was merged with the dark theme pr (https://github.com/CQCL/pytket-circuit-renderer/pull/25)

**Pull request closed without merging**
